import { ExpertiseDomainType } from "@/sharing-enum/spotlight/spotlight.enum";

export const expertiseDomains = [
  {
    enum: ExpertiseDomainType.TECH,
    label: "Tech",
    bgColor: "bg-gray-blue-50",
    textColor: "text-gray-blue-700",
  },
  {
    enum: ExpertiseDomainType.AI,
    label: "Intelligence Artificielle",
    bgColor: "bg-violet-50",
    textColor: "text-violet-700",
  },
  {
    enum: ExpertiseDomainType.FINTECH,
    label: "Fintech",
    bgColor: "bg-emerald-50",
    textColor: "text-emerald-700",
  },
  {
    enum: ExpertiseDomainType.HEALTHTECH,
    label: "Healthtech",
    bgColor: "bg-rose-50",
    textColor: "text-rose-700",
  },
  {
    enum: ExpertiseDomainType.EDTECH,
    label: "Edtech",
    bgColor: "bg-sky-50",
    textColor: "text-sky-700",
  },
  {
    enum: ExpertiseDomainType.GREENTECH,
    label: "Greentech & Climat",
    bgColor: "bg-green-50",
    textColor: "text-green-700",
  },
  {
    enum: ExpertiseDomainType.ECOMMERCE,
    label: "E-commerce & Retail",
    bgColor: "bg-orange-50",
    textColor: "text-orange-700",
  },
  {
    enum: ExpertiseDomainType.SOCIALIMPACT,
    label: "Impact Social",
    bgColor: "bg-pink-50",
    textColor: "text-pink-700",
  },
  {
    enum: ExpertiseDomainType.LEGALTECH,
    label: "Legaltech & RegTech",
    bgColor: "bg-slate-50",
    textColor: "text-slate-700",
  },
  {
    enum: ExpertiseDomainType.PROPTECH,
    label: "Immobilier & Proptech",
    bgColor: "bg-amber-50",
    textColor: "text-amber-700",
  },
  {
    enum: ExpertiseDomainType.FOODTECH,
    label: "Foodtech & AgriTech",
    bgColor: "bg-lime-50",
    textColor: "text-lime-700",
  },
  {
    enum: ExpertiseDomainType.MOBILITY,
    label: "Mobilité & Transport",
    bgColor: "bg-cyan-50",
    textColor: "text-cyan-700",
  },
  {
    enum: ExpertiseDomainType.GAMING,
    label: "Gaming & Esport",
    bgColor: "bg-indigo-50",
    textColor: "text-indigo-700",
  },
  {
    enum: ExpertiseDomainType.MEDIA,
    label: "Média & Créativité",
    bgColor: "bg-fuchsia-50",
    textColor: "text-fuchsia-700",
  },
  {
    enum: ExpertiseDomainType.CYBERSECURITY,
    label: "Cybersécurité",
    bgColor: "bg-red-50",
    textColor: "text-red-700",
  },
  {
    enum: ExpertiseDomainType.BIOTECH,
    label: "Biotech & Sciences",
    bgColor: "bg-teal-50",
    textColor: "text-teal-700",
  },
  {
    enum: ExpertiseDomainType.WEB3,
    label: "Web3 & Blockchain",
    bgColor: "bg-purple-50",
    textColor: "text-purple-700",
  },
  {
    enum: ExpertiseDomainType.HR,
    label: "RH & Future of Work",
    bgColor: "bg-blue-50",
    textColor: "text-blue-700",
  },
  {
    enum: ExpertiseDomainType.DESIGN,
    label: "Design & Créativité",
    bgColor: "bg-yellow-50",
    textColor: "text-yellow-700",
  },
  {
    enum: ExpertiseDomainType.MARKETING,
    label: "Marketing & Growth",
    bgColor: "bg-warning-50",
    textColor: "text-warning-700",
  },
  {
    enum: ExpertiseDomainType.BUSINESS,
    label: "Business & Strategy",
    bgColor: "bg-primary-50",
    textColor: "text-primary-700",
  },
  {
    enum: ExpertiseDomainType.LUXURY,
    label: "Luxe",
    bgColor: "bg-stone-50",
    textColor: "text-stone-700",
  },
  {
    enum: ExpertiseDomainType.BEAUTY,
    label: "Beauté & Cosmétique",
    bgColor: "bg-pink-50",
    textColor: "text-pink-700",
  },
  {
    enum: ExpertiseDomainType.SPORTS,
    label: "Sport",
    bgColor: "bg-orange-50",
    textColor: "text-orange-700",
  },
  {
    enum: ExpertiseDomainType.QUANTUM,
    label: "Quantique",
    bgColor: "bg-violet-50",
    textColor: "text-violet-700",
  },
  {
    enum: ExpertiseDomainType.ADTECH,
    label: "Adtech & Publicité",
    bgColor: "bg-amber-50",
    textColor: "text-amber-700",
  },
  {
    enum: ExpertiseDomainType.URBAN,
    label: "Ville & Urbanisme",
    bgColor: "bg-slate-50",
    textColor: "text-slate-700",
  },
  {
    enum: ExpertiseDomainType.INSURTECH,
    label: "Insurtech",
    bgColor: "bg-cyan-50",
    textColor: "text-cyan-700",
  },
  {
    enum: ExpertiseDomainType.OTHER,
    label: "Autre",
    bgColor: "bg-gray-50",
    textColor: "text-gray-700",
  },
];
