import { z } from 'zod';

// Schema pour une image (logo ou cover)
const LinkedInImageSchema = z.object({
  url: z.string(),
  width: z.number().optional(),
  height: z.number().optional(),
  expiresAt: z.number().optional(),
});

// Schema pour une location
const LinkedInLocationSchema = z.object({
  country: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  geographicArea: z.string().optional().nullable(),
  line1: z.string().optional().nullable(),
  line2: z.string().optional().nullable(),
  postalCode: z.string().optional().nullable(),
  headquarter: z.boolean().optional().nullable(),
  description: z.string().optional().nullable(),
  parsed: z
    .object({
      text: z.string().optional().nullable(),
      countryCode: z.string().nullable().optional(),
      regionCode: z.string().nullable().optional(),
      country: z.string().optional().nullable(),
      countryFull: z.string().optional().nullable(),
      state: z.string().optional().nullable(),
      city: z.string().optional().nullable(),
    })
    .optional()
    .nullable(),
});

// Schema pour une industrie
const LinkedInIndustrySchema = z.object({
  id: z.string().nullable().optional(),
  name: z.string().optional(),
});

// Schema pour foundedOn
const LinkedInFoundedOnSchema = z.object({
  year: z.number().optional().nullable(),
  month: z.number().optional().nullable(),
  day: z.number().optional().nullable(),
});

// Schema pour employeeCountRange
const LinkedInEmployeeCountRangeSchema = z.object({
  start: z.number().optional(),
  end: z.number().optional(),
});

// Schema principal pour un profil LinkedIn Company
export const LinkedInCompanySchema = z.object({
  id: z.string().optional(),
  universalName: z.string().optional(),
  linkedinUrl: z.string().optional(),
  name: z.string(),
  tagline: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
  logo: z.string().optional().nullable(),
  foundedOn: LinkedInFoundedOnSchema.optional().nullable(),
  employeeCount: z.number().optional().nullable(),
  employeeCountRange: LinkedInEmployeeCountRangeSchema.optional().nullable(),
  followerCount: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  companyType: z.string().optional().nullable(),
  locations: z.array(LinkedInLocationSchema).optional().default([]),
  specialities: z.array(z.string()).optional().default([]),
  industries: z.array(LinkedInIndustrySchema).optional().default([]),
  logos: z.array(LinkedInImageSchema).optional().default([]),
  backgroundCover: z.string().optional().nullable(),
  backgroundCovers: z.array(LinkedInImageSchema).optional().default([]),
  autoGenerated: z.boolean().optional(),
  callToActionUrl: z.string().optional().nullable(),
  similarOrganizations: z.array(z.any()).optional().default([]),
  originalQuery: z
    .object({
      search: z.string().optional(),
      location: z.string().optional(),
    })
    .optional(),
  requestId: z.string().optional(),
});

// Type TypeScript dérivé du schema
export type LinkedInCompany = z.infer<typeof LinkedInCompanySchema>;

// Schema pour la réponse Apify (array de companies)
export const ApifyLinkedInCompanyResponseSchema = z.array(
  LinkedInCompanySchema,
);

// Type pour la réponse
export type ApifyLinkedInCompanyResponse = z.infer<
  typeof ApifyLinkedInCompanyResponseSchema
>;
