export enum DiscordChannel {
  OPS_ALERTS = 'OPS_ALERTS',
  OPS_INSCRIPTIONS = 'OPS_INSCRIPTIONS',
  OPS_FEEDBACK = 'OPS_FEEDBACK',
}

export const DISCORD_CHANNEL_ENV_MAP: Record<DiscordChannel, string> = {
  [DiscordChannel.OPS_ALERTS]: 'DISCORD_WEBHOOK_OPS_ALERTS',
  [DiscordChannel.OPS_INSCRIPTIONS]: 'DISCORD_WEBHOOK_OPS_INSCRIPTIONS',
  [DiscordChannel.OPS_FEEDBACK]: 'DISCORD_WEBHOOK_OPS_FEEDBACK',
};

export const EMBED_COLORS = {
  ERROR: 0xff4444,
  WARNING: 0xffaa00,
  SUCCESS: 0x00cc66,
  INFO: 0x5865f2,
  REPORT: 0xff6b6b,
  FEEDBACK_BUG: 0xff4444,
  FEEDBACK_SUGGESTION: 0x5865f2,
  FEEDBACK_COMMENT: 0x00cc66,
  FEEDBACK_FUNCTIONAL: 0xffaa00,
} as const;
