export enum Sort {
  NEWEST = 'NEWEST',
  POPULAR = 'POPULAR',
  INTERESTING = 'INTERESTING',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
}

export enum Tags {
  FUNDAMENTALS = 'FUNDAMENTALS',
  MARKET = 'MARKET',
  MARKETING = 'MARKETING',
  SALES = 'SALES',
  SCALING_AND_GROWTH = 'SCALING_AND_GROWTH',
  FUNDING_AND_INVESTMENT = 'FUNDING_AND_INVESTMENT',
  LEGAL = 'LEGAL',
  HUMAN_RESOURCES_AND_TEAM = 'HUMAN_RESOURCES_AND_TEAM',
  PRODUCT = 'PRODUCT',
  TECHNOLOGY = 'TECHNOLOGY',
  CUSTOMER = 'CUSTOMER',
  BUILD_IN_PUBLIC = 'BUILD_IN_PUBLIC',
}

export enum DiscussionType {
  DISCUSSION = 'DISCUSSION',
  POLL = 'POLL',
  POLL_MULTIPLE = 'POLL_MULTIPLE',
}

export enum Reaction {
  COTILLON = 'COTILLON',
  CRY = 'CRY',
  EYES = 'EYES',
  HEART = 'HEART',
  LAUGH = 'LAUGH',
  ROCKET = 'ROCKET',
  SMILE = 'SMILE',
  THINKING = 'THINKING',
  THUMBS_DOWN = 'THUMBS_DOWN',
  THUMBS_UP = 'THUMBS_UP',
}
