// Valeurs alignées sur ce que le backend accepte réellement
// (discussion list DTO @IsIn + list-discussion.handler). Les anciennes valeurs
// POPULAR/INTERESTING/WEEK/MONTH étaient rejetées en 400 par l'API.
export enum Sort {
  NEWEST = 'NEWEST',
  MOST_UPVOTED = 'MOST_UPVOTED',
  MOST_ANSWERED = 'MOST_ANSWERED',
  MOST_VIEWED = 'MOST_VIEWED',
}

export enum Tags {
  FUNDAMENTALS = 'FUNDAMENTALS',
  MARKET = 'MARKET',
  MARKETING = 'MARKETING',
  SALES = 'SALES',
  SCALING_AND_GROWTH = 'SCALING_AND_GROWTH',
  FUNDING_AND_INVESTMENT = 'FUNDING_AND_INVESTMENT',
  LEGAL = 'LEGAL',
  HUMAN_RESOURCES_AND_TEAM = 'HUMAN_RESOURCES_AND_TEAM',
  PRODUCT = 'PRODUCT',
  TECHNOLOGY = 'TECHNOLOGY',
  CUSTOMER = 'CUSTOMER',
  BUILD_IN_PUBLIC = 'BUILD_IN_PUBLIC',
}

export enum DiscussionType {
  DISCUSSION = 'DISCUSSION',
  POLL = 'POLL',
  POLL_MULTIPLE = 'POLL_MULTIPLE',
}

export enum Reaction {
  COTILLON = 'COTILLON',
  CRY = 'CRY',
  EYES = 'EYES',
  HEART = 'HEART',
  LAUGH = 'LAUGH',
  ROCKET = 'ROCKET',
  SMILE = 'SMILE',
  THINKING = 'THINKING',
  THUMBS_DOWN = 'THUMBS_DOWN',
  THUMBS_UP = 'THUMBS_UP',
}
