/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    team: Team;
    releases: Release;
    contact: Contact;
    feedback: Feedback;
    'recent-updates': RecentUpdate;
    'bug-reports': BugReport;
    waitlist: Waitlist;
    newsletter: Newsletter;
    'spontaneous-applications': SpontaneousApplication;
    resumes: Resume;
    articles: Article;
    categories: Category;
    tags: Tag;
    'media-articles': MediaArticle;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    'recent-updates': RecentUpdatesSelect<false> | RecentUpdatesSelect<true>;
    'bug-reports': BugReportsSelect<false> | BugReportsSelect<true>;
    waitlist: WaitlistSelect<false> | WaitlistSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    'spontaneous-applications': SpontaneousApplicationsSelect<false> | SpontaneousApplicationsSelect<true>;
    resumes: ResumesSelect<false> | ResumesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'media-articles': MediaArticlesSelect<false> | MediaArticlesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'fr';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  image: number | Media;
  bio: string;
  category: 'Founder' | 'Product' | 'Tech' | 'Community' | 'other';
  socials?:
    | {
        type: 'linkedin' | 'twitter' | 'github' | 'medium' | 'dribbble';
        url: string;
        id?: string | null;
      }[]
    | null;
  content?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  /**
   * Format: v1.2.0
   */
  version: string;
  date: string;
  summary: string;
  isLatest?: boolean | null;
  changes: {
    /**
     * Type of change
     */
    type: 'feature' | 'improvement' | 'bugfix' | 'security';
    title: string;
    description: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  category: 'technical' | 'account' | 'feature' | 'billing' | 'partnership' | 'other';
  message: string;
  status?: ('new' | 'in-progress' | 'resolved' | 'archived') | null;
  notes?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User feedback submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  category: 'feature' | 'bug' | 'ux' | 'content' | 'other';
  feedbackText: string;
  /**
   * Email of the user who submitted feedback (if provided)
   */
  userEmail?: string | null;
  status?: ('new' | 'under-review' | 'planned' | 'implemented' | 'rejected' | 'archived') | null;
  priority?: ('low' | 'medium' | 'high' | 'critical') | null;
  internalNotes?: string | null;
  submittedAt?: string | null;
  /**
   * Has this feedback been added to the product roadmap?
   */
  addedToRoadmap?: boolean | null;
  /**
   * Link to related feedback submissions
   */
  relatedFeedback?: (number | Feedback)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recent platform updates to display on the feedback page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recent-updates".
 */
export interface RecentUpdate {
  id: number;
  title: string;
  description: string;
  status: 'Launched' | 'In Progress' | 'Planned';
  /**
   * Ex: "Last week", "Coming soon", "Q2 2024"
   */
  date: string;
  /**
   * Lower numbers appear first
   */
  order: number;
  basedOnFeedback?: boolean | null;
  /**
   * Select feedback entries that inspired this update
   */
  relatedFeedback?: (number | Feedback)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bug reports submitted by users or internal team
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bug-reports".
 */
export interface BugReport {
  id: number;
  title: string;
  category: 'ui' | 'functionality' | 'performance' | 'account' | 'mobile' | 'other';
  priority: 'low' | 'medium' | 'high';
  stepsToReproduce: string;
  expectedBehavior: string;
  actualBehavior: string;
  additionalInformation?: string | null;
  status?: ('new' | 'in-review' | 'in-progress' | 'resolved' | 'closed') | null;
  submittedAt?: string | null;
  internalNotes?: string | null;
  /**
   * Developer assigned to fix this bug
   */
  assignedTo?: string | null;
  /**
   * Link to related bug reports
   */
  relatedBugs?: (number | BugReport)[] | null;
  /**
   * Version where this bug was fixed
   */
  fixedInVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist".
 */
export interface Waitlist {
  id: number;
  /**
   * Email address of the person joining the waitlist
   */
  email: string;
  job: 'founder' | 'investor' | 'aspiring-founder' | 'student' | 'startup-employee' | 'other';
  source: 'linkedin' | 'product-hunt' | 'twitter' | 'friend' | 'google' | 'other';
  goal: 'find-cofounders' | 'gain-visibility' | 'access-funding' | 'learn-resources' | 'discover-events' | 'other';
  /**
   * Status of this waitlist entry
   */
  status?: ('pending' | 'approved' | 'invited' | 'active') | null;
  /**
   * Admin notes about this waitlist entry
   */
  notes?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subscribers to the newsletter
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  /**
   * The subscriber email address
   */
  email: string;
  /**
   * The current status of this subscriber
   */
  status: 'active' | 'inactive' | 'unsubscribed' | 'bounced';
  /**
   * Where the subscriber signed up from
   */
  source?: ('website_footer' | 'newsletter_page' | 'blog_popup' | 'manual_import' | 'other') | null;
  /**
   * When the user subscribed to the newsletter
   */
  subscribedAt: string;
  /**
   * When the last newsletter was sent to this subscriber
   */
  lastSentAt?: string | null;
  /**
   * Subscriber content preferences
   */
  preferences?: {
    weeklyDigest?: boolean | null;
    productUpdates?: boolean | null;
    events?: boolean | null;
  };
  /**
   * Internal notes about this subscriber (not visible to subscribers)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Spontaneous job applications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spontaneous-applications".
 */
export interface SpontaneousApplication {
  id: number;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  /**
   * Applicant email address
   */
  email: string;
  /**
   * Applicant phone number
   */
  phone?: string | null;
  preferredDepartment: 'Engineering' | 'Product' | 'Design' | 'Marketing' | 'Sales' | 'Operations' | 'HR' | 'Finance';
  currentRole: string;
  yearsOfExperience: number;
  socialProfiles?: {
    linkedin?: string | null;
    github?: string | null;
  };
  message: string;
  resume: number | Media;
  status?: ('new' | 'under_review' | 'contacted' | 'interview_scheduled' | 'rejected' | 'hired') | null;
  /**
   * Notes for internal team review (not visible to applicants)
   */
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes/CVs from job applicants
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes".
 */
export interface Resume {
  id: number;
  /**
   * Full name of the candidate
   */
  candidateName: string;
  firstName: string;
  lastName: string;
  /**
   * Contact email of the candidate
   */
  email: string;
  /**
   * Current role or position the candidate is applying for
   */
  position?: string | null;
  /**
   * Department the candidate is applying to
   */
  department?: string | null;
  /**
   * Linked job application if available
   */
  application?: (number | null) | SpontaneousApplication;
  /**
   * Internal notes about this resume (not visible to candidates)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  submittedAt?: string | null;
  status?: ('new' | 'under_review' | 'shortlisted' | 'rejected' | 'hired') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Afficher l'article sur la navbar
   */
  displayOnNavbar?: boolean | null;
  /**
   * Le titre de l'article
   */
  title: string;
  /**
   * L'identifiant unique utilisé dans l'URL (ex: ai-startup-guide)
   */
  slug: string;
  /**
   * Un résumé court de l'article (140-160 caractères)
   */
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * L'image principale de l'article (recommandé: 1200x630)
   */
  featuredImage: number | Media;
  /**
   * La catégorie principale de l'article
   */
  category: number | Category;
  /**
   * L'auteur de l'article (membre de l'équipe)
   */
  author?: (number | null) | Team;
  /**
   * Titre spécifique de l'auteur pour cet article (optionnel, utilisé si différent du rôle habituel)
   */
  authorTitle?: string | null;
  /**
   * Les tags associés à l'article
   */
  tags?: (number | Tag)[] | null;
  /**
   * Mettre en avant cet article sur la page blog
   */
  isFeatured?: boolean | null;
  /**
   * Temps de lecture estimé (ex: 5 min)
   */
  readTime?: string | null;
  /**
   * Nombre de vues de l'article
   */
  views?: number | null;
  /**
   * Articles connexes à suggérer (max 3)
   */
  relatedArticles?: (number | Article)[] | null;
  status: 'draft' | 'review' | 'published';
  /**
   * Date de publication de l'article
   */
  publishedAt?: string | null;
  /**
   * SEO Metadata
   */
  seo?: {
    /**
     * Titre SEO personnalisé (si différent du titre principal)
     */
    title?: string | null;
    /**
     * Description SEO (si différente de la description principale)
     */
    description?: string | null;
    /**
     * Mots-clés séparés par des virgules
     */
    keywords?: string | null;
    /**
     * Image pour partage sur réseaux sociaux (si différente de l'image principale)
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Nom de la catégorie (ex: AI & Tech)
   */
  name: string;
  /**
   * L'identifiant unique pour la catégorie
   */
  slug: string;
  /**
   * Description courte de la catégorie
   */
  description?: string | null;
  /**
   * Code couleur HEX (ex: #5E6AD2)
   */
  color?: string | null;
  /**
   * Nom de l'icône Lucide à utiliser (ex: Rocket, Star, etc.)
   */
  icon?: string | null;
  /**
   * Image d'en-tête pour la page de catégorie
   */
  featuredImage?: (number | null) | MediaArticle;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-articles".
 */
export interface MediaArticle {
  id: number;
  /**
   * Texte alternatif pour l'accessibilité
   */
  alt: string;
  /**
   * Légende à afficher sous l'image (optionnel)
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    featured?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Nom du tag (ex: Machine Learning)
   */
  name: string;
  /**
   * L'identifiant unique pour le tag
   */
  slug: string;
  /**
   * Description optionnelle du tag
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'contact';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'recent-updates';
        value: number | RecentUpdate;
      } | null)
    | ({
        relationTo: 'bug-reports';
        value: number | BugReport;
      } | null)
    | ({
        relationTo: 'waitlist';
        value: number | Waitlist;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'spontaneous-applications';
        value: number | SpontaneousApplication;
      } | null)
    | ({
        relationTo: 'resumes';
        value: number | Resume;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media-articles';
        value: number | MediaArticle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  bio?: T;
  category?: T;
  socials?:
    | T
    | {
        type?: T;
        url?: T;
        id?: T;
      };
  content?:
    | T
    | {
        point?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  version?: T;
  date?: T;
  summary?: T;
  isLatest?: T;
  changes?:
    | T
    | {
        type?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  category?: T;
  message?: T;
  status?: T;
  notes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  category?: T;
  feedbackText?: T;
  userEmail?: T;
  status?: T;
  priority?: T;
  internalNotes?: T;
  submittedAt?: T;
  addedToRoadmap?: T;
  relatedFeedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recent-updates_select".
 */
export interface RecentUpdatesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  date?: T;
  order?: T;
  basedOnFeedback?: T;
  relatedFeedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bug-reports_select".
 */
export interface BugReportsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  priority?: T;
  stepsToReproduce?: T;
  expectedBehavior?: T;
  actualBehavior?: T;
  additionalInformation?: T;
  status?: T;
  submittedAt?: T;
  internalNotes?: T;
  assignedTo?: T;
  relatedBugs?: T;
  fixedInVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist_select".
 */
export interface WaitlistSelect<T extends boolean = true> {
  email?: T;
  job?: T;
  source?: T;
  goal?: T;
  status?: T;
  notes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  source?: T;
  subscribedAt?: T;
  lastSentAt?: T;
  preferences?:
    | T
    | {
        weeklyDigest?: T;
        productUpdates?: T;
        events?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spontaneous-applications_select".
 */
export interface SpontaneousApplicationsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  preferredDepartment?: T;
  currentRole?: T;
  yearsOfExperience?: T;
  socialProfiles?:
    | T
    | {
        linkedin?: T;
        github?: T;
      };
  message?: T;
  resume?: T;
  status?: T;
  internalNotes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes_select".
 */
export interface ResumesSelect<T extends boolean = true> {
  candidateName?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  position?: T;
  department?: T;
  application?: T;
  notes?: T;
  submittedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  displayOnNavbar?: T;
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  authorTitle?: T;
  tags?: T;
  isFeatured?: T;
  readTime?: T;
  views?: T;
  relatedArticles?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  icon?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-articles_select".
 */
export interface MediaArticlesSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        featured?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}